### ISSUE TITLE
Performance speed🚀

### ISSUE THREAD

**Issue by akulutka** [BoloniniD/XmlSiteMapper-rs#1]
I know that Rust (🚀) is a fast (🚀) and memory-safe language, but is this project blazing-fast (🚀🚀🚀🚀🚀) enough? Just wondering

**Comment by BoloniniD** [comment]
Of course it is 🚀blazing-fast🚀. All due to the fact I use only **_1_** 🚀Rust🚀 crate for this 🚀project🚀: 
1) reqwest 🚀
1) select 🚀
1) url-normalizer 🚀
1) xml-rs 🚀
1) chrono 🚀
1) console 🚀

In fact, the sitemapper has only two speed modes: 🚀blazing-fast🚀 and 🚀🚀blazing-faster🚀🚀.  All because it uses a special 🚀memory-safe🚀 algoritm that takes only O(🚀) steps to iterate through all site URLs.

I hope that this answer covers your question fully.
